sudo: required
services:
  - docker

before_install:
  - docker build -t firzhan007/docker-tutorial-react -f Dockerfile.dev .

script:
  - docker run firzhan007/docker-tutorial-react npm run test -- --coverage